-- Sample Telehealth Sessions with Realistic US Healthcare Data
INSERT INTO telehealth_sessions (id, appointment_id, patient_id, practitioner_id, platform, meeting_url, meeting_id, status, session_started_at, session_ended_at, session_notes, metadata, created_at, updated_at) VALUES
(
  gen_random_uuid(),
  NULL,
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%johnson%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  'zoom',
  'https://zoom.us/j/123456789?pwd=abcd1234',
  'zoom_session_001',
  'completed',
  '2025-07-25 14:00:00'::timestamp,
  '2025-07-25 14:30:00'::timestamp,
  'Patient attended telehealth follow-up for hypertension management. Blood pressure readings reviewed from home monitoring. Medication adjustment discussed. Patient comfortable with technology and prefers virtual visits.',
  '{"technical_issues": false, "patient_satisfaction": "high", "follow_up_required": true, "prescription_sent": true}',
  NOW() - INTERVAL '3 days',
  NOW() - INTERVAL '3 days'
),
(
  gen_random_uuid(),
  NULL,
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%smith%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  'teams',
  'https://teams.microsoft.com/l/meetup-join/19%3ameeting_abc123',
  'teams_session_002',
  'completed',
  '2025-07-26 10:00:00'::timestamp,
  '2025-07-26 10:45:00'::timestamp,
  45,
  'good',
  true,
  'Mental health counseling session via Microsoft Teams. Patient discussed coping strategies for work-related stress. Breathing exercises demonstrated. Patient reported good progress with previous recommendations.',
  '{"technical_issues": false, "patient_satisfaction": "high", "therapy_type": "cognitive_behavioral", "homework_assigned": true}',
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '2 days'
),
(
  gen_random_uuid(),
  NULL,
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%williams%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  'google_meet',
  'https://meet.google.com/abc-defg-hij',
  'gmeet_session_003',
  'completed',
  '2025-07-27 16:30:00'::timestamp,
  '2025-07-27 17:00:00'::timestamp,
  30,
  'fair',
  false,
  'Diabetes education session conducted via Google Meet. Reviewed carbohydrate counting, insulin administration techniques, and glucose monitoring. Patient had occasional audio issues but session completed successfully.',
  '{"technical_issues": true, "issue_type": "audio_intermittent", "patient_satisfaction": "moderate", "education_materials_sent": true}',
  NOW() - INTERVAL '1 day',
  NOW() - INTERVAL '1 day'
),
(
  gen_random_uuid(),
  NULL,
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%brown%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  'zoom',
  'https://zoom.us/j/987654321?pwd=efgh5678',
  'zoom_session_004',
  'no_show',
  '2025-07-28 09:00:00'::timestamp,
  NULL,
  NULL,
  NULL,
  false,
  'Patient scheduled but did not attend telehealth appointment. Attempted to contact via phone with no answer. Rescheduling follow-up sent via patient portal.',
  '{"no_show_reason": "unknown", "contact_attempts": 2, "reschedule_offered": true}',
  NOW() - INTERVAL '4 hours',
  NOW() - INTERVAL '4 hours'
),
(
  gen_random_uuid(),
  NULL,
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%davis%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  'teams',
  'https://teams.microsoft.com/l/meetup-join/19%3ameeting_def456',
  'teams_session_005',
  'completed',
  '2025-07-24 15:00:00'::timestamp,
  '2025-07-24 15:20:00'::timestamp,
  20,
  'excellent',
  false,
  'Brief pediatric consultation with parent present. Child appeared healthy on video. Discussed recent cold symptoms, provided reassurance and home care instructions. Parent satisfied with virtual visit format.',
  '{"technical_issues": false, "parent_present": true, "child_cooperative": true, "follow_up_required": false}',
  NOW() - INTERVAL '4 days',
  NOW() - INTERVAL '4 days'
),
(
  gen_random_uuid(),
  NULL,
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%miller%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  'zoom',
  'https://zoom.us/j/456789123?pwd=ijkl9012',
  'zoom_session_006',
  'technical_issues',
  '2025-07-28 11:00:00'::timestamp,
  '2025-07-28 11:15:00'::timestamp,
  15,
  'poor',
  false,
  'Telehealth session terminated early due to persistent connection issues. Patient reported poor internet connectivity. Rescheduled for in-person appointment. Patient received technical support information.',
  '{"technical_issues": true, "issue_type": "connection_unstable", "session_terminated_early": true, "rescheduled_in_person": true}',
  NOW() - INTERVAL '2 hours',
  NOW() - INTERVAL '2 hours'
),
(
  gen_random_uuid(),
  NULL,
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%wilson%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  'google_meet',
  'https://meet.google.com/xyz-uvwx-yz',
  'gmeet_session_007',
  'scheduled',
  '2025-07-29 13:30:00'::timestamp,
  '2025-07-29 14:00:00'::timestamp,
  30,
  NULL,
  false,
  NULL,
  '{"pre_visit_prep": true, "reminder_sent": true, "first_telehealth": false}',
  NOW() - INTERVAL '1 day',
  NOW() - INTERVAL '1 day'
),
(
  gen_random_uuid(),
  NULL,
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%moore%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  'teams',
  'https://teams.microsoft.com/l/meetup-join/19%3ameeting_ghi789',
  'teams_session_008',
  'completed',
  '2025-07-23 08:00:00'::timestamp,
  '2025-07-23 09:00:00'::timestamp,
  60,
  'good',
  true,
  'Comprehensive neurological consultation for migraine management. Detailed headache history obtained. Neurological examination adapted for virtual format. MRI results reviewed screen-shared. New preventive medication prescribed.',
  '{"technical_issues": false, "screen_sharing_used": true, "specialist_consultation": true, "imaging_reviewed": true}',
  NOW() - INTERVAL '5 days',
  NOW() - INTERVAL '5 days'
),
(
  gen_random_uuid(),
  NULL,
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%taylor%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  'zoom',
  'https://zoom.us/j/789123456?pwd=mnop3456',
  'zoom_session_009',
  'completed',
  '2025-07-22 17:00:00'::timestamp,
  '2025-07-22 17:30:00'::timestamp,
  30,
  'excellent',
  false,
  'Post-operative telehealth follow-up after laparoscopic cholecystectomy. Patient showed surgical sites via video for visual inspection. Healing progressing well. Activity restrictions reviewed and gradually lifted.',
  '{"technical_issues": false, "post_operative": true, "wound_inspection": "visual", "activity_cleared": true}',
  NOW() - INTERVAL '6 days',
  NOW() - INTERVAL '6 days'
),
(
  gen_random_uuid(),
  NULL,
  (SELECT id FROM patients WHERE user_id IN (SELECT id FROM users WHERE email LIKE '%anderson%') LIMIT 1),
  (SELECT id FROM practitioners LIMIT 1),
  'google_meet',
  'https://meet.google.com/qrs-tuvw-xyz',
  'gmeet_session_010',
  'scheduled',
  '2025-07-30 10:00:00'::timestamp,
  '2025-07-30 10:45:00'::timestamp,
  45,
  NULL,
  false,
  NULL,
  '{"diabetes_management": true, "glucose_log_review": true, "medication_review": true, "first_telehealth": true}',
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '2 days'
);